#!/bin/sh

# Check if file-system is mounted on given mount point and is writable
#
# Usage: ./check_disk_mount_rw <path> <file_system_id>
#
# Description:
#
# This plugin will check if there exist '.nagios-disk-id' file in given path
# and if this file is writable.
#
# Install:
#
# 1. Create uniq ID for this mount point
#
#    # cat /proc/sys/kernel/random/uuid > /.nagios-disk-id
#
# 2. Make sure this file will be accessible for nagios
#
#    # chown nagios /.nagios-disk-id
#    # chmod 600 /.nagios-disk-id
#
# 3. Create NRPE entry
#
#    # echo "command[my-check-disk-mount-rw-root]=/usr/local/lib/nagios/plugins/check_disk_mount_rw '/' '$(cat /.nagios-disk-id)'"' \
#		>> /etc/nagios/nrpe.d/my_commands.cfg
#

if [ "$#" != 1 ]
then
	echo "Usage: $0 <mount_point> <file_system_id>"
	exit 3
fi

MOUNT="$1"
DISK_ID="$2"
ID_FILE=".nagios-disk-id"

CRITICAL()
{
        echo "CRITICAL: $@"
        exit 2
}

F="${MOUNT}/${ID_FILE}"
test ! -d "${MOUNT}" && CRITICAL "Missing mount point '${MOUNT}'"
test ! -e "${F}" && CRITICAL "Missing ID '${ID_FILE}' file in mount point '${MOUNT}'"
MOUNT_ID=`cut -c -100 < "${F}" | head -n 1`
test "x${DISK_ID}" != "x${MOUNT_ID}" && CRITICAL "ID Missmatch"
test -O "${F}" || CRITICAL "File '${ID_FILE}' owner does not match `id`"
test -w "${F}" || CRITICAL "File '${ID_FILE}' is not Writeable"
touch "${F}" || CRITICAL "Disk RO"

echo "DISK OK"
exit 0
