#!/bin/sh


if [ "$#" != 1 ]
then
	echo "Usage: $0 <mount_point> <file_system_id>"
	exit 3
fi

MOUNT="$1"
DISK_ID="$2"
ID_FILE=".nagios-disk-id"

CRITICAL()
{
        echo "CRITICAL: $@"
        exit 2
}

F="${MOUNT}/${ID_FILE}"
test ! -d "${MOUNT}" && CRITICAL "Missing mount point '${MOUNT}'"
test ! -e "${F}" && CRITICAL "Missing ID '${ID_FILE}' file in mount point '${MOUNT}'"
MOUNT_ID=`cut -c -100 < "${F}" | head -n 1`
test "x${DISK_ID}" != "x${MOUNT_ID}" && CRITICAL "ID Missmatch"
test -O "${F}" || CRITICAL "File '${ID_FILE}' owner does not match `id`"
test -w "${F}" || CRITICAL "File '${ID_FILE}' is not Writeable"
touch "${F}" || CRITICAL "Disk RO"

echo "DISK OK"
exit 0
